- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: clone a repo
    git: repo=https://github.com/Sonal0409/AnsibleDockerdemo.git dest=/tmp/mygitrepo1
  - name: build docker file
    command: chdir=/tmp/mygitrepo1 docker build -t myapp:0.01.test1 .
  - name: create container
    command: docker run -itd -P myapp:0.01.test1
